### PR TITLE
Suggest using half-width Katakana

### PR DESCRIPTION
**Pull request by medicalwei**
As a Chinese-writing person I found the drop using some Chinese characters weird.
I suggest using half-width Katakana as the characters, since Matrix does so (but these are horizontally-inverted in Matrix film.)

### CODE REVIEW

**Comment by pazdera** [comment]
Hey @medicalwei. Thanks for your suggestion! Personally, I think it looks more interesting visually with the large Chinese characters, but I can't read them. May I ask, what do you find weird?

**Comment by medicalwei** [comment]
The first weird thing is that they share the same component (田), which I guess is that you picked these characters from a range of codepoints.

Second, each Chinese character has a highly chance to imply a meaning, while Latin or Japanese Katakana character don't.

If you would like to use Chinese characters I would suggest using these:
甲乙丙丁戊己庚辛壬癸
子丑寅卯辰巳午未申酉戌亥

These are used for counting or recording date and time in Chinese traditions.

**Comment by pazdera** [comment]
Right, I see. Thanks so much for pointing that out!

I replaced the Chinese characters with the set you suggested here https://github.com/KanoComputing/kano-matrix/commit/0747b0d3c094811db2ca847b92f1c393d857318b

**Comment by medicalwei** [comment]
Thank you!

**Pull request closed without merging**
